name = "SpawnACU"
uid = "fspaw274-v001-55b4-92b6-64398e7ge43f"
version = 1
copyright = "MIT License"
description = "Select the Spawn ACU AI, and at the start of the game its ACU will be transferred over to a human player on the same time"
author = "maudlin27"
url = ""
icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
