---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/10/2022 22:38
---
function TransferACU(oOriginalBrain)
    WaitSeconds(4)
    LOG('Finished waiting, will try and transfer')
    for iBrain, oBrain in ArmyBrains do
        if not(oBrain == oOriginalBrain) and IsAlly(oOriginalBrain:GetArmyIndex(), oBrain:GetArmyIndex()) and oBrain.BrainType == 'Human' then
            LOG('Repru of oBrain='..repru(oBrain)..'; repr of oOriginalBrain='..repru(oOriginalBrain))
            local tUnitsToTransfer = oOriginalBrain:GetListOfUnits(categories.COMMAND, false, true)
            if tUnitsToTransfer then
                for iUnit, oUnit in tUnitsToTransfer do
                    LOG('iUnit='..iUnit..'; oUnit='..oUnit.UnitId)
                    local tSpawnLocation = {oUnit:GetPosition()[1], oUnit:GetPosition()[2], oUnit:GetPosition()[3]}
                    local sSpawnID = oUnit.UnitId
                    oUnit:Destroy()
                    local oNewUnit = CreateUnit(sSpawnID, oBrain.Army, tSpawnLocation[1], tSpawnLocation[2], tSpawnLocation[3], 0, 0, 0, 0, 'Land')
                    LOG('Attempted to create unit with sSpawnID='..sSpawnID..' for army '..oBrain.Army..' at location '..repru(tSpawnLocation))
                end
            else
                LOG('No units to transfer')
            end
        end
    end
end
