---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/10/2022 22:38
---
function TransferACU(oOriginalBrain)
    WaitSeconds(4)
    for iBrain, oBrain in tArmyBrains do
        if IsAlly(oOriginalBrain:GetArmyIndex(), oBrain:GetArmyIndex()) then
            import('/lua/SimUtils.lua').TransferUnitsOwnership(oOriginalBrain:GetListOfUnits(categories.COMMAND, false, true), oBrain:GetArmyIndex(), false)
            LOG('TransferACU: Given order to transfer ownership of all units owned by brain '..oOriginalBrain.Nickname..' to '..oBrain.Nickname)
        end
    end
end
